<script>
    // =============== // METADATA // ===============
    let pageTitle = "Privacy Policy";
    let pageDescription = "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.";
</script>
<!-- =============== // PAGE TITLE AND METADATA // ===============  -->

<svelte:head>
	<title>{pageTitle}</title>
	<meta name="description" content={pageDescription} />
    <meta name="twitter:title" property="og:title" itemprop="name" content={pageTitle} />
    <meta name="twitter:description" property="og:description" itemprop="description" content={pageDescription} />
</svelte:head>

<div class="container mx-auto p-6 max-w-4xl bg-white rounded-2xl shadow-lg dark:bg-gray-900 dark:text-white transition-all duration-300">
    <h1 class="text-4xl font-extrabold mb-6 text-gray-900 dark:text-white bg-gradient-to-r from-blue-500 to-teal-500 bg-clip-text text-transparent">Privacy Policy</h1>
    <div class="space-y-6 text-gray-700 dark:text-gray-300">
        <p class="text-sm italic">Last updated: March 14, 2025</p>
        <p class="leading-relaxed">This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p class="leading-relaxed">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" class="text-blue-600 hover:underline dark:text-blue-400">Free Privacy Policy Generator</a>.</p>
        
        <!-- Umami Tracking Mention -->
        <p class="leading-relaxed">We use <span class="font-semibold">Umami</span> for basic event tracking to help us understand how our Service is used and to improve your experience. Umami is a privacy-focused analytics tool, and you can learn more about their privacy practices at <a href="https://umami.is/privacy" target="_blank" class="text-blue-600 hover:underline dark:text-blue-400">https://umami.is/privacy</a>.</p>

        <h2 class="text-2xl font-semibold mt-8 text-gray-800 dark:text-gray-200 border-b-2 border-blue-500 pb-2">Interpretation and Definitions</h2>
        <h3 class="text-xl font-medium text-gray-700 dark:text-gray-300">Interpretation</h3>
        <p class="leading-relaxed">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h3 class="text-xl font-medium text-gray-700 dark:text-gray-300">Definitions</h3>
        <p class="leading-relaxed">For the purposes of this Privacy Policy:</p>
        <ul class="list-disc pl-6 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Dam Levels.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: South Africa</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to Dam Levels, accessible from <a href="damlevels.co.za" rel="external nofollow noopener" target="_blank" class="text-blue-600 hover:underline dark:text-blue-400">damlevels.co.za</a></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 class="text-2xl font-semibold mt-8 text-gray-800 dark:text-gray-200 border-b-2 border-blue-500 pb-2">Collecting and Using Your Personal Data</h2>
        <h3 class="text-xl font-medium text-gray-700 dark:text-gray-300">Types of Data Collected</h3>
        <h4 class="text-lg font-medium text-gray-600 dark:text-gray-400">Personal Data</h4>
        <p class="leading-relaxed">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul class="list-disc pl-6 space-y-2">
            <li>Usage Data</li>
        </ul>

        <h4 class="text-lg font-medium text-gray-600 dark:text-gray-400">Usage Data</h4>
        <p class="leading-relaxed">Usage Data is collected automatically when using the Service.</p>
        <p class="leading-relaxed">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p class="leading-relaxed">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
        <p class="leading-relaxed">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

        <h4 class="text-lg font-medium text-gray-600 dark:text-gray-400">Tracking Technologies and Cookies</h4>
        <p class="leading-relaxed">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <ul class="list-disc pl-6 space-y-2">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>
        <p class="leading-relaxed">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" target="_blank" class="text-blue-600 hover:underline dark:text-blue-400">Free Privacy Policy website</a> article.</p>
        <p class="leading-relaxed">We use both Session and Persistent Cookies for the purposes set out below:</p>
        <ul class="list-disc pl-6 space-y-4">
            <li>
                <p><strong>Necessary / Essential Cookies</strong></p>
                <p>Type: Session Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
            </li>
            <li>
                <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
            </li>
            <li>
                <p><strong>Functionality Cookies</strong></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
            </li>
        </ul>
        <p class="leading-relaxed">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

        <!-- Remaining sections follow similar enhancements -->
        <h3 class="text-xl font-medium text-gray-700 dark:text-gray-300">Use of Your Personal Data</h3>
        <p class="leading-relaxed">The Company may use Personal Data for the following purposes:</p>
        <ul class="list-disc pl-6 space-y-2">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <!-- Add other list items similarly -->
        </ul>

        <!-- Continue enhancing other sections with similar Tailwind classes -->
        <h2 class="text-2xl font-semibold mt-8 text-gray-800 dark:text-gray-200 border-b-2 border-blue-500 pb-2">Contact Us</h2>
        <p class="leading-relaxed">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul class="list-disc pl-6 space-y-2">
            <li>By email: <a href="mailto:toast@happybread.net" class="text-blue-600 hover:underline dark:text-blue-400">toast@happybread.net</a></li>
        </ul>
    </div>
</div>